name: 'Without Self Hosted PHP'
author: velioglu
description: 'GitHub Action for PHP - Without Self Hosted'
branding:
  color: 'purple'
  icon: 'play-circle'
inputs:
  php-version:
    description: 'Setup PHP version.'
    required: false
  php-version-file:
    description: 'Setup PHP version from a file.'
    required: false
  extensions:
    description: 'Setup PHP extensions.'
    required: false
  ini-file:
    description: 'Set base ini file.'
    required: false
    default: 'production'
  ini-values:
    description: 'Add values to php.ini.'
    required: false
  coverage: 
    description: 'Setup code coverage driver.'
    required: false
  tools:
    description: 'Setup popular tools globally.'
    required: false
outputs:
  php-version:
    description: 'PHP version in semver format'
runs:
  using: 'node20'
  main: 'dist/index.js'
